list: $/diveramkt/floatingbanner/models/capturaemails/columns.yaml
modelClass: Diveramkt\Floatingbanner\Models\CapturaEmails
title: CapturaEmails
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'diveramkt/floatingbanner/capturaemails/update/:id'
