name: Popups
modelClass: Diveramkt\Floatingbanner\Models\Popup
form: $/diveramkt/floatingbanner/models/popup/fields.yaml
defaultRedirect: 'diveramkt/floatingbanner/popups'
create:
    redirect: 'diveramkt/floatingbanner/popups/update/:id'
    redirectClose: 'diveramkt/floatingbanner/popups/update/:id'
update:
    redirect: 'diveramkt/floatingbanner/popups'
    redirectClose: 'diveramkt/floatingbanner/popups'
preview: {  }
